# Generated by Django 4.0.4 on 2022-11-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
