# Generated by Django 4.0.4 on 2022-11-21 16:01

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_firstname_customuser_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default=app.models.id_gen, max_length=30, primary_key=True, serialize=False),
        ),
    ]
