# Generated by Django 4.0.4 on 2022-11-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
