# Generated by Django 4.0.4 on 2022-12-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
