# Generated by Django 4.0.4 on 2022-12-19 00:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_device_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationhistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='immunizationhistory',
            name='vaccine',
        ),
        migrations.AddField(
            model_name='immunizationhistory',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.vaccine'),
        ),
    ]
