# Generated by Django 4.0.4 on 2023-01-27 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_immunizationhistory_veterinarian'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='immunizationhistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='immunizationhistory',
            name='next_vaccination_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='immunizationhistory',
            unique_together={('pet', 'pet_age', 'next_vaccination_date')},
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
            options={
                'unique_together': {('customer', 'token')},
            },
        ),
    ]
