# Generated by Django 4.0.4 on 2023-01-27 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_immunizationhistory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunizationhistory',
            name='dose',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
