# Generated by Django 4.0.4 on 2023-01-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_immunizationhistory_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunizationhistory',
            name='pet_age',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
