# Generated by Django 4.0.4 on 2023-01-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_immunizationhistory_pet_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunizationhistory',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vaccine'),
        ),
    ]
