# Generated by Django 4.0.4 on 2023-01-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_immunizationhistory_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunizationhistory',
            name='veterinarian',
            field=models.CharField(default='Dr. Ong', max_length=50),
        ),
    ]
