# Generated by Django 4.0.4 on 2023-01-27 21:45

import app.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_immunizationhistory_veterinarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunizationhistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[app.models.validate_past_date]),
        ),
    ]
