# Generated by Django 4.0.4 on 2023-01-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_immunizationhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationhistory',
            name='attachment',
            field=models.ImageField(blank=True, upload_to='records/'),
        ),
    ]
