# Generated by Django 4.0.4 on 2023-03-09 11:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_immunizationhistory_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunizationhistory',
            name='owner_actions',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='immunizationhistory',
            name='veterinary_actions',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('purpose', models.IntegerField(default=1)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pet')),
            ],
        ),
    ]
