# Generated by Django 4.0.4 on 2023-08-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_immunizationhistory_owner_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.IntegerField(default=2),
        ),
    ]
