# Generated by Django 4.0.4 on 2023-08-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_appointment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fully Paid'), (2, 'Balance'), (3, 'Prmisory Note')], default=2),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='purpose',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fully Paid'), (2, 'Balance'), (3, 'Prmisory Note')], default=1),
        ),
    ]
