# Generated by Django 4.0.4 on 2023-08-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_item_mrp_remove_item_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='createdat',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='updatedat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='createdat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updatedat',
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
