# Generated by Django 4.0.4 on 2023-08-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_brand_createdat_remove_brand_updatedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=75),
        ),
    ]
