# Generated by Django 4.0.4 on 2023-09-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brandid',
        ),
        migrations.RemoveField(
            model_name='item',
            name='productid',
        ),
        migrations.AddField(
            model_name='item',
            name='brand_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
