# Generated by Django 4.0.4 on 2023-09-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_item_brandid_remove_item_productid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='purpose',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Check Up'), (2, 'Grooming')], default=1),
        ),
    ]
