# Generated by Django 4.0.4 on 2023-09-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_item_options_alter_appointment_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='purpose',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Check Up'), (2, 'Immunization'), (3, 'Vaccination'), (4, 'Deworming'), (5, 'Home Service'), (6, 'Grooming')], default=1),
        ),
    ]
