# Generated by Django 4.0.4 on 2023-09-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_appointment_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fully Paid'), (2, 'Balance'), (3, 'Promisory Note')], default=2),
        ),
    ]
